chore:ci/cd

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -6,7 +6,7 @@ on:
       - deploy_git
 
 jobs:
-  deploy_portpolio:
+  deploy_front:
     runs-on: ubuntu-latest
     steps:
       - name: checkout repository
@@ -17,3 +17,69 @@ jobs:
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./board/index
+
+  deploy_back:
+    runs-on: ubuntu-latest
+    steps:
+      - name: checkout repository
+        uses: actions/checkout@v4
+
+      - name: Add SSH key
+        uses: webfactory/ssh-agent@v0.5.4
+        with:
+          ssh-private-key: ${{ secrets.EC2_KEY }}
+
+      - name: Ensure SSH directory exists
+        runs: |
+          mkdir -p ~/.ssh
+          chmod 700 ~/.ssh
+
+      - name: Add SSH known hosts
+        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
+
+      - name: check mysql
+        run: |
+
+      - name: Copy Files to EC2
+        run: |
+          ssh ${{ secrets.EC2_USER }}${{ secrets.EC2_HOST }}
+            rm -rf /var/www/teamproject1
+            mkdir /var/www/teamproject1
+            mkdir /var/www/teamproject1/config
+            mkdir /var/www/teamproject1/sessions
+          rsync -avz -e "ssh" ./backEnd ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/teamproject1
+          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
+          export NVM_DIR="$HOME/.nvm"
+          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" || {
+          echo "nvm.sh not found"
+          exit 1
+          }
+          cd  /var/www/teamproject1
+          npm i --production
+          cd /var/www/teamproject1
+          echo PORT=3080 > .env
+          echo NODE_ENV=deploy >> .env
+          cd /
+          cd /var/www/teamproject1/config
+          echo { > config.json
+          echo "deploy": { >> config.json
+          echo  "username": "${{ secrets.EC2_MYSQL_USERNAME }}" >> config.json
+          echo  "password": "${{ secrets.EC2_MYSQL_PASSWORD }}" >> config.json
+          echo  "database": "${{ secrets.EC2_MYSQL_DATABASE }}" >> config.json
+          echo  "host": "127.0.0.1" >> config.json
+          echo  "port": "${{ secrets.EC2_MYSQL_PORT }}" >> config.json
+          echo  "dialect": "mysql" >> config.json
+          echo  } >> config.json
+          echo } >> config.json'
+
+      - name: Start Server
+        run: |
+          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
+          export NVM_DIR="$HOME/.nvm"
+          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" || {
+          echo "nvm.sh not found"
+          exit 1
+          }        
+          npm install -g pm2          
+          pm2 stop teamproject1
+          pm2 start /var/www/teamproject1/server.js --name teamproject1'
